# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eca99653ad1fc3afa55aaa16a2960d3cb086db67a30ebeb4a5f12e7e0923c9a3322de12d32c1971f77095ac38374703ae853066802729b56ac28843ae95ae6c2

test:
  secret_key_base: 360329a050e256f1982689ae89adfd6d248b44da1e405bc1a824f68eeb197adc8599a3fc358b6ad4066dd2c4f945e1170ccdccbd30a095fd11b62fa1b6690138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
